# Play to prepare a jail
- name: Setup Jail
  hosts: "{{ target }}"

  vars:
    ansible_ssh_private_key_file: ~/.ssh/ssh_jail
    ansible_user: "root"

  environment:
    ASSUME_ALWAYS_YES: "yes"

  pre_tasks:
    - assert:
        that:
          - "'host' not in group_names"
          - "'jail' in group_names"

  roles:
    - {role: jail, tags: jail}
    - {role: common, tags: common}
    - {role: sshd, tags: sshd}
    # - {role: pf, tags: pf}
