- name: Setup Host
  hosts: "{{ target }}"

  pre_tasks:
    - assert:
        that:
          - "'jail' not in group_names"

  roles:
    - {role: host, tags: host}
    - {role: provision, tags: provision}
