helix_database_username: helix
helix_database_password: helix
helix_database_host: 192.168.110.10
helix_database_pool_size: 10

helix_environment: 
  HELIX_DB_USER: "{{ helix_database_username }}"
  HELIX_DB_PASS: "{{ helix_database_password }}"
  HELIX_DB_HOST: "{{ helix_database_host }}"
  HELIX_DB_POOL_SIZE: "{{ helix_database_pool_size }}"
  REPLACE_OS_VARS: "true"
  MIX_ENV: "prod"
