- include_role:
    name: utils
    tasks_from: assert
  vars:
    assert_defined:
      - name
      - kvs

- name: Add fact "{{ name }}"
  template:
    src: fact.j2
    dest: "/etc/ansible/facts.d/{{ name }}.fact"
    mode: 0755
    owner: phoebe
    group: phoebe
  become: true

- set_fact:
    name: null
    kvs: null
