- name: Install plugins
  jenkins_plugin:
    name: "{{ item }}"
    state: latest
    jenkins_home: "{{ jenkins_home }}"
    url: https://ci.hackerexperience.com
    params:
      url_username: "{{ private_jenkins_user }}"
      url_password: "{{ private_jenkins_password }}"
  with_items:
    - saferestart
    - html5-notifier-plugin
    - embeddable-build-status
    - global-build-status
    - greeballs
    - ws-cleanup
    - lockable-resources
    - ghprb
    - workflow-aggregator
    - pipeline-milestone-step
    - s3
    - ssh-slaves
    - timestamper
    - build-pipeline-plugin
    - blueocean
    - github
    # Required stuff / dependencies
    - ant
    - antisamy-markup-formatter
    - authentication-tokens
    - aws-java-sdk
    - blueocean-autofavorite
    - blueocean-commons
    - blueocean-config
    - blueocean-dashboard
    - blueocean-display-url
    - blueocean-events
    - blueocean-git-pipeline
    - blueocean-github-pipeline
    - blueocean-i18n
    - blueocean-jwt
    - blueocean-personalization
    - blueocean-pipeline-api-impl
    - blueocean-pipeline-editor
    - blueocean-rest-impl
    - blueocean-rest
    - blueocean-web
    - bouncycastle-api
    - branch-api
    - cloudbees-folder
    - conditional-buildstep
    - copyartifact
    - credentials-binding
    - credentials
    - display-url-api
    - docker-commons
    - docker-workflow
    - durable-task
    - external-monitor-job
    - favorite
    - git-client
    - git-server
    - git
    - github-api
    - github-branch-source
    - github-organization-folder
    - icon-shim
    - jackson2-api
    - javadoc
    - jquery-detached
    - jquery
    - junit
    - ldap
    - mailer
    - matrix-auth
    - matrix-project
    - maven-plugin
    - metrics
    - pam-auth
    - parameterized-trigger
    - pipeline-build-step
    - pipeline-github-lib
    - pipeline-graph-analysis
    - pipeline-input-step
    - pipeline-model-api
    - pipeline-model-definition
    - pipeline-model-extensions
    - pipeline-stage-step
    - pipeline-stage-tags-metadata
    - pipeline-stage-view
    - plain-credentials
    - pubsub-light
    - resource-disposer
    - run-condition
    - scm-api
    - script-security
    - sse-gateway
    - ssh-agent
    - ssh-credentials
    - structs
    - token-macro
    - variant
    - windows-slaves
    - workflow-api
    - workflow-basic-steps
    - workflow-cps
    - workflow-cps-global-lib
    - workflow-job
    - workflow-multibranch
    - workflow-scm-step
    - workflow-step-api
    - workflow-support
    - workflow-durable-task-step

  notify: restart jenkins
  become: true
  # become_user: jenkins
