- include_role:
    name: config
    tasks_from: creator
  vars:
    dest: /etc/pf.conf
    mode: 0644
    validate: "/sbin/pfctl -vnf %s"

- command: /usr/bin/true
  delegate_to: localhost
  notify: restart pf
  changed_when: assembled_fragment.changed
