- include_role:
    name: config
    tasks_from: creator
  vars:
    dest: /etc/rc.local
    mode: 0774
    validate: "/bin/sh %s" 

- command: /bin/sh /etc/rc.local
  when: assembled_fragment.changed
