# \/ GCE Only
# - name: Add mappings to /etc/hosts
#   lineinfile:
#     path: /etc/hosts
#     line: "{{ item.ip }} {{ item.name }}"
#   with_items:
#     - { name: localhost, ip: "127.0.0.1" }
#     - { name: localhost, ip: "::1" }
#   become: true

- name: Install some basic stuff
  pkgng:
    name: "{{ item }}"
  with_items:
    - wget
    - ca_root_nss
    - bash
    - sudo
  become: true

- name: Add ansible user
  user:
    name: "{{ user }}"
    shell: "{{ user_shell }}"
    home: "{{ user_home }}"
    password: "{{ user_password }}"
    groups: wheel
    append: yes
  become: true
  no_log: true

- name: Add sudoers template
  template:
    src: sudoers.j2
    dest: /usr/local/etc/sudoers
    owner: root
    group: wheel
    mode: 0440
    backup: yes
  become: true

- name: Ensure ansible facts directory exists
  file:
    path: /etc/ansible/facts.d
    recurse: yes
    state: directory
  become: true

- name: Track these tasks for changes
  include_role:
    name: utils
    tasks_from: tracker
  vars:
    from_role: common
    track_file: configure
