# - name: Ensure .ssh directory exists
#   file:
#     path: "/home/{{ item.name }}/.ssh"
#     recurse: yes
#     state: directory
#     owner: "{{ item.name }}"
#     group: "{{ item.name }}"
#   become: true
#   with_items: "{{ sshd_users }}"
  

- name: Add ssh user keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.public_key }}"
  with_items: "{{ sshd_users }}"
  become: true

- name: sshd configuration file template
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: yes
    owner: 0
    group: 0
    mode: 0644
    validate: '/usr/sbin/sshd -T -f %s'
  become: true
  notify:
  - restart sshd
 
